// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq5FifxaFZQKUN6L-3-w2OdsqeouwkUNY',
    appId: '1:839977485872:web:9e7fab284242719e490ff5',
    messagingSenderId: '839977485872',
    projectId: 'qubit-7cc0f',
    authDomain: 'qubit-7cc0f.firebaseapp.com',
    storageBucket: 'qubit-7cc0f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu6siBdeKvNP9ahYuB5sl5qysj2_M9-G4',
    appId: '1:839977485872:android:fd4b285b0207ce1b490ff5',
    messagingSenderId: '839977485872',
    projectId: 'qubit-7cc0f',
    storageBucket: 'qubit-7cc0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRbhd21iWbYJ0SON_qvcYMBKZ7MxKDkLE',
    appId: '1:839977485872:ios:96200224327e5b49490ff5',
    messagingSenderId: '839977485872',
    projectId: 'qubit-7cc0f',
    storageBucket: 'qubit-7cc0f.firebasestorage.app',
    androidClientId: '839977485872-idbtcp4kk8tidrsp1bptc05805m5c4u6.apps.googleusercontent.com',
    iosClientId: '839977485872-t67mn20g991rcal86cipk67p3hokpcrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.qubitGeo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRbhd21iWbYJ0SON_qvcYMBKZ7MxKDkLE',
    appId: '1:839977485872:ios:96200224327e5b49490ff5',
    messagingSenderId: '839977485872',
    projectId: 'qubit-7cc0f',
    storageBucket: 'qubit-7cc0f.firebasestorage.app',
    androidClientId: '839977485872-idbtcp4kk8tidrsp1bptc05805m5c4u6.apps.googleusercontent.com',
    iosClientId: '839977485872-t67mn20g991rcal86cipk67p3hokpcrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.qubitGeo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq5FifxaFZQKUN6L-3-w2OdsqeouwkUNY',
    appId: '1:839977485872:web:4e0e95357c9694fa490ff5',
    messagingSenderId: '839977485872',
    projectId: 'qubit-7cc0f',
    authDomain: 'qubit-7cc0f.firebaseapp.com',
    storageBucket: 'qubit-7cc0f.firebasestorage.app',
  );
}
